### ISSUE TITLE
Question about "segfault during garbage collection"

### ISSUE THREAD

**Issue by maxballenger** [pycopia/ssh2-python3#2]
Hi, I see on the README that this fork of ssh2-python is supposed to fix "a segfault during garbage collection in certain situations". I may be encountering this. Could you provide any more information about this issue? Here is what I am seeing with ssh2-python 0.22.0:

`Thread 144 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffef7e96700 (LWP 8370)]
0x0000000000000000 in ?? ()
(gdb) wher
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff2bbf91b in _libssh2_channel_free () from /opt/aeva/py3env/lib/python3.6/site-packages/ssh2/../ssh2_python.libs/libssh2-55f304ca.so.1.0.1
#2  0x00007ffff2bbfa07 in libssh2_channel_free () from /opt/aeva/py3env/lib/python3.6/site-packages/ssh2/../ssh2_python.libs/libssh2-55f304ca.so.1.0.1
#3  0x00007ffff154386d in __pyx_pf_4ssh2_7channel_7Channel_2__dealloc__ (__pyx_v_self=0x7ffef96c3c88) at ssh2/channel.c:1575
#4  __pyx_pw_4ssh2_7channel_7Channel_3__dealloc__ (__pyx_v_self=<ssh2.channel.Channel at remote 0x7ffef96c3c88>) at ssh2/channel.c:1547
#5  __pyx_tp_dealloc_4ssh2_7channel_Channel (o=<ssh2.channel.Channel at remote 0x7ffef96c3c88>) at ssh2/channel.c:7775
#6  0x0000000000576737 in frame_tp_clear.lto_priv () at ../Objects/frameobject.c:548
#7  0x00000000005a3c0e in delete_garbage (old=<optimized out>, collectable=<optimized out>) at ../Modules/gcmodule.c:864`

and so on. Could this be the same bug you reference?

**Comment by kdart** [comment]
That looks like it. Hard to tell if it's the exact same or slightly different one, but the context is right.

**Comment by maxballenger** [comment]
Thank you! Can you point me to any more information about the bug you originally found, like a Github issue or a commit that fixes it?
